CREATE OR REPLACE VIEW REGIME_UTILISATEUR AS
	SELECT U.*, R.IDREGIME, R.DEBUTREGIME, R.FINREGIME, R.POIDSOBJECTIFREGIME
	FROM REGIME R
    JOIN UTILISATEUR U ON R.IDUTILISATEUR = U.IDUTILISATEUR;
CREATE OR REPLACE VIEW REGIME_ALIMENTATION AS
	SELECT R.*, A.IDALIMENTATION, REPASALIMENTATION, BOISSONALIMENTATION, PERIODEALIMENTATION, DATEALIMENTATION
	FROM ALIMENTATION A
	JOIN REGIME_UTILISATEUR R ON A.IDREGIME = R.IDREGIME;
CREATE OR REPLACE VIEW REGIME_SPORT AS
	SELECT R.*, RS.IDSPORTREGIME, RS.IDSPORT, DATESPORTREGIME, RYTHMESPORTREGIME, LIBELLESPORT, ACTIVITESSPORT
	FROM SPORTREGIME RS
	JOIN REGIME_UTILISATEUR R ON RS.IDREGIME = R.IDREGIME
	JOIN SPORT S ON RS.IDSPORT = S.IDSPORT;
CREATE OR REPLACE VIEW REGIME_POIDS AS
	SELECT R.*, IDPOIDS, VALEURPOIDS, DATEPOIDS
	FROM POIDS P
	JOIN REGIME_UTILISATEUR R ON P.IDREGIME = R.IDREGIME;
CREATE OR REPLACE VIEW CONSEIL_SPORT AS
	SELECT CS.*, LIBELLESPORT, ACTIVITESSPORT
	FROM SPORTCONSEIL CS
	JOIN SPORT S ON CS.IDSPORT = S.IDSPORT;

CREATE VIEW LASTPOIDS AS
	SELECT * 
	FROM POIDS P
	INNER JOIN
    (SELECT IDREGIME, MAX(DATEPOIDS) AS MAXDATEPOIDS
    FROM POIDS
    GROUP BY IDREGIME) L 
	ON P.IDREGIME = L.IDREGIME 
	AND P.DATEPOIDS = L.MAXDATEPOIDS;

CREATE VIEW ANALYSEREGIME
	AS SELECT R.*, 
		COALESCE(SUM(S.RYTHMESPORTREGIME),0) AS RYTHMESPORTTOTAL,
		COALESCE((R.POIDSINITIALREGIME - P.VALEURPOIDS),0) AS POIDSPERDU
	FROM REGIME R
	LEFT JOIN SPORTREGIME S ON S.IDREGIME = R.IDREGIME
	LEFT JOIN LASTPOIDS P ON P.IDREGIME = R.IDREGIME
	GROUP BY R.IDREGIME, POIDSPERDU;

CREATE VIEW ANALYSEUTILISATEUR
	AS SELECT U.*, 
		COALESCE(COUNT(R.IDREGIME),0) AS REGIMETOTAL
	FROM UTILISATEUR U
	LEFT JOIN REGIME R ON U.IDUTILISATEUR = R.IDUTILISATEUR
	GROUP BY U.IDUTILISATEUR, NOMUTILISATEUR, PRENOMUTILISATEUR, DATENAISSANCEUTILISATEUR, 
       EMAILUTILISATEUR, SEXEUTILISATEUR, PASSWORDUTILISATEUR, ADRESSEUTILISATEUR;
	  
CREATE VIEW ANALYSESPORT
	AS SELECT S.*, 
		COALESCE(COUNT(C.IDSPORTCONSEIL),0) AS CONSEILTOTAL
	FROM SPORT S
	LEFT JOIN SPORTCONSEIL C ON C.IDSPORT = S.IDSPORT
	GROUP BY S.IDSPORT, LIBELLESPORT, ACTIVITESSPORT;