/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-05-14 21:41:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Utilisateur;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import s6.suiviRegime.modele.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import s6.suiviRegime.utilitaire.*;
import java.time.format.FormatStyle;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Utilisateur/includes/header.jsp", Long.valueOf(1494796225067L));
    _jspx_dependants.put("/Utilisateur/includes/footer.jsp", Long.valueOf(1494785610183L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("s6.suiviRegime.modele");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("s6.suiviRegime.utilitaire");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.time.format.FormatStyle");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("      <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Following You ! Mon Tableau de Bord</title>\r\n");
      out.write("\t<!-- BOOTSTRAP STYLES-->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- FONTAWESOME STYLES-->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- MORRIS CHART STYLES-->\r\n");
      out.write("    <link href=\"/SuiviRegime/js/morris/morris-0.4.3.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- CUSTOM STYLES-->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">Following You !</a> \r\n");
      out.write("            </div>\r\n");
      out.write("\t\t    <div style=\"color: white;\r\n");
      out.write("\t\t\t\t\t\tpadding: 15px 50px 5px 50px;\r\n");
      out.write("\t\t\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\t\t\tfont-size: 16px;\"> \r\n");
      out.write("\t\t\t\tBonjour, ");
 out.print(((Utilisateur)session.getAttribute("user")).getFullName()); 
      out.write("! &nbsp; <a href=\"/SuiviRegime/Utilisateur/Deconnexion\" class=\"btn btn-danger square-btn-adjust\">Deconnexion</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </nav>   \r\n");
      out.write("           <!-- /. NAV TOP  -->\r\n");
      out.write("                <nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"text-center\">\r\n");
      out.write("                    \t<!-- <img src=\"img/find_user.png\" class=\"user-image img-responsive\"/> -->\r\n");
      out.write("                    \t<a><i class=\"fa fa-id-card-o fa-5x\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"active-menu\"  href=\"/SuiviRegime/Utilisateur\"><i class=\"fa fa-dashboard fa-3x\"></i> Tableau de bord</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a  href=\"/SuiviRegime/Utilisateur/Regime\"><i class=\"fa fa-calendar fa-2x\"></i> R&eacute;gimes</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a  href=\"/SuiviRegime/Utilisateur/Poids\"><i class=\"fa fa-line-chart fa-2x\"></i> Poids et &Eacute;volution</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("                        <a   href=\"/SuiviRegime/Utilisateur/Alimentation\"><i class=\"fa fa-cutlery fa-2x\"></i> Alimentation quotidienne</a>\r\n");
      out.write("                    </li>\t\r\n");
      out.write("                      <li  >\r\n");
      out.write("                        <a  href=\"/SuiviRegime/Utilisateur/Sport\"><i class=\"fa fa-heartbeat fa-2x\"></i> Sports</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li  >\r\n");
      out.write("                        <a  href=\"/SuiviRegime/Utilisateur/Conseil\"><i class=\"fa fa-bullhorn fa-2x\"></i> Conseils pratiques</a>\r\n");
      out.write("                    </li>\t\t\t\t\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </nav>  \r\n");
      out.write("        <!-- /. NAV SIDE  -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/jquery.min.js\"></script>\r\n");
      out.write("        <div id=\"page-wrapper\" >");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  Utilisateur user = (Utilisateur)request.getAttribute("user"); 
	AnalyseRegime regime = (AnalyseRegime)request.getAttribute("regimeActif");
	BaseModelePagination liste = (BaseModelePagination)request.getAttribute("listeRegime");
	int pageNumero = (int)request.getAttribute("page");

      out.write("\r\n");
      out.write("            <div id=\"page-inner\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                     <h2>Mon Tableau de Bord</h2>   \r\n");
      out.write("                        <h5>Bonjour ");
 out.print(user.getFullName()); 
      out.write(" , Heureux de vous revoir! </h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>              \r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("                  <hr />\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  ");

                  if(regime != null){ 
      out.write("\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("\t\t                <span class=\"icon-box bg-color-red set-icon\">\r\n");
      out.write("\t\t                    <i class=\"fa fa-clock-o\"></i>\r\n");
      out.write("\t\t                </span>\r\n");
      out.write("\t\t                <div class=\"text-box\" >\r\n");
      out.write("\t\t                    <p class=\"main-text\">");
 out.print(regime.getMinuteSportParSemaineString()); 
      out.write("</p>\r\n");
      out.write("\t\t                    <p class=\"text-muted\">sport par Semaine</p>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t             </div>\r\n");
      out.write("\t\t\t     </div>\r\n");
      out.write("                 <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("\t\t                <span class=\"icon-box bg-color-green set-icon\">\r\n");
      out.write("\t\t                    <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("\t\t                </span>\r\n");
      out.write("\t\t                <div class=\"text-box\" >\r\n");
      out.write("\t\t                    <p class=\"main-text\">");
 out.print(regime.getPoidsObjectif()); 
      out.write(" kg</p>\r\n");
      out.write("\t\t                    <p class=\"text-muted\">Objectif</p>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t             </div>\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("\t\t                <span class=\"icon-box bg-color-brown set-icon\">\r\n");
      out.write("\t\t                    <i class=\"fa fa-sort-amount-desc\"></i>\r\n");
      out.write("\t\t                </span>\r\n");
      out.write("\t\t                <div class=\"text-box\" >\r\n");
      out.write("\t\t                    <p class=\"main-text\">");
 out.print(regime.getPoidsPerduParSemaineString()); 
      out.write("</p>\r\n");
      out.write("\t\t                    <p class=\"text-muted\">&eacute;volution par Semaine</p>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t             </div>\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("\t\t                <span class=\"icon-box bg-color-blue set-icon\">\r\n");
      out.write("\t\t                    <i class=\"fa fa-calendar-o\"></i>\r\n");
      out.write("\t\t                </span>\r\n");
      out.write("\t\t                <div class=\"text-box\" >\r\n");
      out.write("\t\t                    <p class=\"main-text\">");
 out.print(regime.getJourRestant()); 
      out.write(" jours</p>\r\n");
      out.write("\t\t                    <p class=\"text-muted\">Restants</p>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t             </div>\r\n");
      out.write("\t\t     \t</div>\r\n");
      out.write("\t\t    ");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t");
  if(!liste.getListe().isEmpty()){
      out.write("\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted\">Activez un r&eacute;gime pour commencer votre exp&eacute;rience avec Following You !</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t                <div class=\"panel-heading\">\r\n");
      out.write("\t\t                    Liste des r&eacute;gimes clos\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"panel-body\">\r\n");
      out.write("\t\t                    <div class=\"table-responsive\">\r\n");
      out.write("\t\t                        <table class=\"table table-hover\">\r\n");
      out.write("\t\t                            <thead>\r\n");
      out.write("\t\t                                <tr>\r\n");
      out.write("\t\t                                    <th>#</th>\r\n");
      out.write("\t\t                                    <th>D&eacute;but</th>\r\n");
      out.write("\t\t                                    <th>Fin</th>\r\n");
      out.write("\t\t                                    <th>Poids Initial</th>\r\n");
      out.write("\t\t                                    <th>Poids Objectif</th>\r\n");
      out.write("\t\t                                    <th></th>\r\n");
      out.write("\t\t                                </tr>\r\n");
      out.write("\t\t                            </thead>\r\n");
      out.write("\t\t                            <tbody>\r\n");
      out.write("\t\t                            ");
 for(Regime r : (List<Regime>)liste.getListe()){ 
      out.write("\r\n");
      out.write("\t\t                                <tr>\r\n");
      out.write("\t\t                                    <td>");
 out.print(r.getId()); 
      out.write("</td>\r\n");
      out.write("\t\t                                    <td>");
 out.print(r.getDebutString()); 
      out.write("</td>\r\n");
      out.write("\t\t                                    <td>");
 out.print(r.getFinString()); 
      out.write("</td>\r\n");
      out.write("\t\t                                    <td>");
 out.print(r.getPoidsInitialString()); 
      out.write("</td>\r\n");
      out.write("\t\t                                    <td>");
 out.print(r.getPoidsObjectifString()); 
      out.write("</td>\r\n");
      out.write("\t\t                                    <td><a href=\"/SuiviRegime/Utilisateur/Regime/activate?regime.id=");
 out.print(r.getId()); 
      out.write("\" class=\"btn btn-success square-btn-adjust\">activer</a></td>\r\n");
      out.write("\t\t                                </tr>\r\n");
      out.write("\t\t                            ");
 } 
      out.write("\r\n");
      out.write("\t\t                            </tbody>\r\n");
      out.write("\t\t                        </table>\r\n");
      out.write("\t\t                         <ul class=\"pagination\">\r\n");
      out.write("\t\t                         \t");
 for(int i=0; i<liste.getNombrePage();i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"");
 if(i == pageNumero) out.print("active"); 
      out.write("\"><a href=\"?page=");
 out.print(i+1); 
      out.write('"');
      out.write('>');
 out.print(i+1); 
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t </ul> \r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t                       \r\n");
      out.write("\t\t\t\t\t\t        ");
 if(request.getAttribute("erreur") != null){ 
      out.write("    \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"alert alert-danger alert-dismissable fade in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">&times;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <strong>Probl&egrave;me!</strong> ");
 out.print(request.getAttribute("erreur")); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>     \r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t\t            \t</div>\r\n");
      out.write("\t\t            \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"Utilisateur/Regime/add\" class=\"btn btn-danger square-btn-adjust\">Cr&eacute;er votre R&eacute;gime</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("\t            <hr />                \r\n");
      out.write("\t            <div class=\"row\">\r\n");
      out.write("\t                <div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("\t                    <div class=\"panel back-dash\">\r\n");
      out.write("\t                        <i class=\"fa fa-bullhorn fa-2x\"></i><strong> &nbsp; TIPS DU JOUR</strong>\r\n");
      out.write("\t                        ");
 AlimentationConseil tips =  (AlimentationConseil)request.getAttribute("randomTips");
      out.write("\r\n");
      out.write("\t                        <p class=\"text-muted\">");
 out.print(tips.getNom()); 
      out.write("</p>\r\n");
      out.write("\t                        <p>Matin : ");
 out.print(tips.getMatin()); 
      out.write("</p>\r\n");
      out.write("\t                        <p>Midi : ");
 out.print(tips.getMidi()); 
      out.write("</p>\r\n");
      out.write("\t                        <p>Soir : ");
 out.print(tips.getSoir()); 
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                       \r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"col-md-6 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t                    <div class=\"panel \">\r\n");
      out.write("\t\t\t\t          <div class=\"main-temp-back\">\r\n");
      out.write("\t\t\t\t            <div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t              <div class=\"row\">\r\n");
      out.write("\t\t\t\t                <div class=\"col-xs-12 text-left\"> <i class=\"fa fa-cloud fa-3x\"></i> Antananarivo </div>\r\n");
      out.write("\t\t\t\t                <div class=\"col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t                  <div class=\"text-temp\"> ");
 out.print(DateUtil.getInstance().LocalDateToString(LocalDate.now())); 
      out.write(" </div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t              </div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t          </div>\r\n");
      out.write("\t\t          \t\t</div>\r\n");
      out.write("\t                    <div class=\"panel panel-back noti-box\">\r\n");
      out.write("\t                    \t<div class=\"row\">\r\n");
      out.write("\t\t                    \t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t                <span class=\"icon-box bg-color-green set-icon\">\r\n");
      out.write("\t\t\t\t\t                    <i class=\"fa fa-info\"></i>\r\n");
      out.write("\t\t\t\t\t                </span>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t                <div class=\"text-box col-xs-10\" >\r\n");
      out.write("\t\t\t\t                    <p class=\"main-text\">Mes Informations</p>\r\n");
      out.write("\t\t\t\t                    <p class=\"text-muted\">Nom &amp; Pr&eacute;nom : ");
 out.print(user.getFullName()); 
      out.write("<br>\r\n");
      out.write("\t\t                            ");
 out.print(user.getFullDateNaissanceString()); 
      out.write("<br>\r\n");
      out.write("\t\t                            ");
 out.print(user.getSexeString()); 
      out.write("<br>\r\n");
      out.write("\t\t                            Adresse : ");
 out.print(user.getAdresse()); 
      out.write("<br>\r\n");
      out.write("\t\t                            Email : ");
 out.print(user.getEmail()); 
      out.write("</p>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t             \t\t</div>\r\n");
      out.write("\t    \t\t\t</div>              \r\n");
      out.write("\t        \t</div>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("             <!-- /. PAGE INNER  -->\r\n");
      out.write("            </div>\r\n");
      out.write("         <!-- /. PAGE WRAPPER  -->\r\n");
      out.write("        </div>\r\n");
      out.write("     <!-- /. WRAPPER  -->\r\n");
      out.write("    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("    <!-- JQUERY SCRIPTS -->\r\n");
      out.write("      <!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- METISMENU SCRIPTS -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/jquery.metisMenu.js\"></script>   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
