/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-05-17 06:52:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Administrateur.Utilisateur;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import s6.suiviRegime.modele.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.util.List;

public final class detailPoids_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Administrateur/Utilisateur/../includes/header.jsp", Long.valueOf(1494933572914L));
    _jspx_dependants.put("/Administrateur/Utilisateur/../includes/footer.jsp", Long.valueOf(1494806805875L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("s6.suiviRegime.modele");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Admin admin = (Admin)request.getAttribute("admin"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Following You ! Administrateur</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- MetisMenu CSS -->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Morris Charts CSS -->\r\n");
      out.write("    <link href=\"/SuiviRegime/js/morris/morris-0.4.3.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"/SuiviRegime/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"/SuiviRegime\">Following You ! Administration</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("            \t<li>Derni&egrave;re connexion le <b>");
 out.print(admin.getLastLoginString()); 
      out.write("</b></li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"/SuiviRegime/Administrateur/Deconnexion\"><i class=\"fa fa-sign-out fa-fw\"></i> Deconnexion</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- /.navbar-top-links -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/SuiviRegime/Administrateur\"><i class=\"fa fa-dashboard fa-fw\"></i> Tableau de bord</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/SuiviRegime/Administrateur/Utilisateur\"><i class=\"fa fa-group fa-fw\"></i> Utilisateurs</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/SuiviRegime/Administrateur/Sport\"><i class=\"fa fa-heartbeat fa-fw\"></i> Sport</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-bullhorn fa-fw\"></i> Conseils<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"/SuiviRegime/Administrateur/Conseil/Alimentation\">Alimentation</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"/SuiviRegime/Administrateur/Conseil/Sport\">Sport</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.sidebar-collapse -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-static-side -->\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page-wrapper\">");
      out.write('\n');
      out.write('\n');
 
	Utilisateur user = (Utilisateur)request.getAttribute("utilisateur");
	BaseModelePagination liste = (BaseModelePagination)request.getAttribute("liste");
	AnalyseRegime regime = (AnalyseRegime)request.getAttribute("regime");
	int pageNumero = (int)request.getAttribute("page");

      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <h2 class=\"page-header\">Utilisateurs - Poids</h2>\n");
      out.write("                    <ul class=\"breadcrumb\">\n");
      out.write("\t\t\t\t\t  <li><a href=\"/SuiviRegime/Administrateur/Utilisateur\">Utilisateurs</a></li>\n");
      out.write("\t\t\t\t\t  <li><a href=\"/SuiviRegime/Administrateur/Utilisateur/detail?utilisateur.id=");
 out.print(user.getId()); 
      out.write('"');
      out.write('>');
 out.print(user.getFullName()); 
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t  <li class=\"active\">D&eacute;tails Poids</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.col-lg-12 -->\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("            </div>\n");
      out.write("            <!-- /.row -->\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"panel panel-default\">\n");
      out.write("                        <div class=\"panel-heading\">\n");
      out.write("                            D&eacute;tails de r&eacute;gime suivi par l'utilisateur\n");
      out.write("                        </div>\n");
      out.write("                        <!-- /.panel-heading -->\n");
      out.write("                        <div class=\"panel-body\">\n");
      out.write("                        \t<div class=\"col-sm-6\">\n");
      out.write("                        \t\t<p>Nom &amp; Pr&eacute;nom : ");
 out.print(user.getFullName()); 
      out.write("<br>\n");
      out.write("\t\t                            ");
 out.print(user.getFullDateNaissanceString()); 
      out.write("<br>\n");
      out.write("\t\t                            ");
 out.print(user.getSexeString()); 
      out.write("<br>\n");
      out.write("\t\t                            Adresse : ");
 out.print(user.getAdresse()); 
      out.write("<br>\n");
      out.write("\t\t                            Email : ");
 out.print(user.getEmail()); 
      out.write("</p>\n");
      out.write("                        \t</div>\n");
      out.write("                        \t<table width=\"100%\" class=\"table table-striped table-hover\">\n");
      out.write("                                <thead>\n");
      out.write("\t\t                                <tr>\n");
      out.write("\t\t                                    <th>#</th>\n");
      out.write("\t\t                                    <th>D&eacute;but</th>\n");
      out.write("\t\t                                    <th>Fin</th>\n");
      out.write("\t\t                                    <th>Jours Restants</th>\n");
      out.write("\t\t                                    <th>Poids Initial</th>\n");
      out.write("\t\t                                    <th>Poids Objectif</th>\n");
      out.write("\t\t                                    <th>Moyenne de poids perdu</th>\n");
      out.write("\t\t                                    <th>Moyenne de sport pratiqu&eacute;</th>\n");
      out.write("\t\t                                </tr>\n");
      out.write("\t\t                            </thead>\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>");
 out.print(regime.getId()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getDebutString()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getFinString()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getJourRestant()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getPoidsInitial()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getPoidsObjectif()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getPoidsPerduParSemaineString()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(regime.getMinuteSportParSemaineString()); 
      out.write("</td>\n");
      out.write("                                        <td class=");
 if(regime.isActive()){ 
      out.write("\"success\"> Actif <span class=\"glyphicon glyphicon-ok\"></span>\n");
      out.write("                                        \t");
 }else{ 
      out.write("\"warning\"> Inactif <span class=\"glyphicon glyphicon-remove\"></span>\n");
      out.write("                                        \t");
 } 
      out.write("</td>\n");
      out.write("                                        <td><a class=\"btn btn-default\" href=\"/SuiviRegime/Administrateur/Utilisateur/Regime/Alimentation?regime.id=");
 out.print(regime.getId()); 
      out.write("\">D&eacute;tails aliment.</a></td>\n");
      out.write("                                        <td><a class=\"btn btn-default\" href=\"/SuiviRegime/Administrateur/Utilisateur/Regime/Sport?regime.id=");
 out.print(regime.getId()); 
      out.write("\">D&eacute;tails sport</a></td>\n");
      out.write("                                        <td><a class=\"btn btn-danger\" href=\"/SuiviRegime/Administrateur/Utilisateur/Regime/delete?id=");
 out.print(regime.getId()); 
      out.write("\">Supprimer</a></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        \t");
 if(liste.getListe() != null && !liste.getListe().isEmpty()){ 
      out.write("\n");
      out.write("                            <table width=\"100%\" class=\"table table-striped table-hover\">\n");
      out.write("                                <thead>\n");
      out.write("\t\t                                <tr>\n");
      out.write("\t\t                                    <th>#</th>\n");
      out.write("\t\t                                    <th>Date</th>\n");
      out.write("\t\t                                    <th>Poids</th>\n");
      out.write("\t\t                                </tr>\n");
      out.write("\t\t                            </thead>\n");
      out.write("                                <tbody>\n");
      out.write("                                ");
 for(Poids a : (List<Poids>)liste.getListe()){ 
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>");
 out.print(a.getId()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(a.getDateString()); 
      out.write("</td>\n");
      out.write("                                        <td>");
 out.print(a.getValeur()); 
      out.write("</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                            <!-- /.table-responsive -->\n");
      out.write("\t\t                         <ul class=\"pagination\">\n");
      out.write("\t\t                         \t");
 for(int i=0; i<liste.getNombrePage();i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"");
 if(i == pageNumero) out.print("active"); 
      out.write("\"><a href=\"?page=");
 out.print(i+1); 
      out.write('"');
      out.write('>');
 out.print(i+1); 
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t </ul> \n");
      out.write("                        </div>\n");
      out.write("                        <!-- /.panel-body -->\n");
      out.write("                        ");
 }
                            else out.print("Aucun poids enregistr&eacute; pour l'instant"); 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.panel -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /.col-lg-12 -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.row -->\n");
      out.write("                 \n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#page-wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/jquery.metisMenu.js\"></script>   \r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"/SuiviRegime/js/sb-admin-2.min.js\"></script>    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("<!DOCTYPE html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
