/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-05-13 09:15:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html >\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Authentification Utilisateur</title>    \n");
      out.write("    <link rel=\"stylesheet\" href=\"/SuiviRegime/css/normalize.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/SuiviRegime/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/SuiviRegime/css/login.css\">\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <div class=\"form\">\n");
      out.write("      \n");
      out.write("      <ul class=\"tab-group\">\n");
      out.write("        <li class=\"tab\"><a href=\"#inscription\">Inscription</a></li>\n");
      out.write("        <li class=\"tab active\"><a href=\"#connexion\">Connexion</a></li>\n");
      out.write("      </ul>\n");
      out.write("      \n");
      out.write("      <div class=\"tab-content\">\n");
      out.write("        <div id=\"inscription\">   \n");
      out.write("          <h1>Inscrivez vous gratuitement</h1>\n");
      out.write("          \n");
      out.write("          <form action=\"/SuiviRegime/Utilisateur/new\" method=\"post\">\n");
      out.write("          \n");
      out.write("\t          <div class=\"top-row\">\n");
      out.write("\t            <div class=\"field-wrap\">\n");
      out.write("\t              <label>\n");
      out.write("\t                Nom<span class=\"req\">*</span>\n");
      out.write("\t              </label>\n");
      out.write("\t              <input type=\"text\" required autocomplete=\"off\" name=\"utilisateur.nom\" />\n");
      out.write("\t            </div>\n");
      out.write("\t        \n");
      out.write("\t            <div class=\"field-wrap\">\n");
      out.write("\t              <label>\n");
      out.write("\t                Pr&eacute;nom<span class=\"req\">*</span>\n");
      out.write("\t              </label>\n");
      out.write("\t              <input type=\"text\" required autocomplete=\"off\" name=\"utilisateur.prenom\" />\n");
      out.write("\t            </div>\n");
      out.write("\t          </div>\n");
      out.write("\t\n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Adresse Email<span class=\"req\">*</span>\n");
      out.write("\t            </label>\n");
      out.write("\t            <input type=\"email\" required autocomplete=\"off\" name=\"utilisateur.email\" />\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Date de naissance<span class=\"req\">*</span>\n");
      out.write("\t            </label>\n");
      out.write("\t            <input type=\"date\" required autocomplete=\"off\" name=\"dateNaissance\"/>\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Femme\n");
      out.write("\t            </label>\n");
      out.write("\t\t\t\t  <input type=\"radio\" name=\"utilisateur.sexe\" value=\"F\" checked/>\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Homme\n");
      out.write("\t            </label>\n");
      out.write("\t              <input type=\"radio\" name=\"utilisateur.sexe\" value=\"M\"/>\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Mot de passe<span class=\"req\">*</span>\n");
      out.write("\t            </label>\n");
      out.write("\t            <input type=\"password\" required autocomplete=\"off\" name=\"password\"/>\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Confirmer votre Mot de passe<span class=\"req\">*</span>\n");
      out.write("\t            </label>\n");
      out.write("\t            <input type=\"password\" required autocomplete=\"off\"/>\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"field-wrap\">\n");
      out.write("\t            <label>\n");
      out.write("\t              Adresse\n");
      out.write("\t            </label>\n");
      out.write("\t            <input type=\"text\" autocomplete=\"off\" name=\"utilisateur.adresse\"/>\n");
      out.write("\t          </div>\t          \n");
      out.write("\t          <button type=\"submit\" class=\"button button-block\">S'inscrire</button>\n");
      out.write("\t          \n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div id=\"connexion\">   \n");
      out.write("          <h1>Vous revoilà!</h1>\n");
      out.write("          \n");
      out.write("          <form action=\"/SuiviRegime/Utilisateur/Connexion\" method=\"post\">\n");
      out.write("          \n");
      out.write("            <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Adresse Email<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input type=\"email\"required name=\"email\"/>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Mot de passe<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input type=\"password\"required autocomplete=\"off\" name=\"password\"/>\n");
      out.write("          </div>\n");
      out.write("           ");
 if(request.getAttribute("erreur") != null){ 
      out.write("    \n");
      out.write("\t\t  <div class=\"alert alert-danger alert-dismissable fade in\">\n");
      out.write("\t\t    <a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">&times;</a>\n");
      out.write("\t\t    <strong>Probl&egrave;me!</strong> ");
 out.print(request.getAttribute("erreur")); 
      out.write("\n");
      out.write("\t\t  </div>     \n");
      out.write("\t\t  ");
 } 
      out.write("\n");
      out.write("          <button class=\"button button-block\">Se Connecter</button>\n");
      out.write("          \n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div><!-- tab-content -->\n");
      out.write("      \n");
      out.write("\t</div> <!-- /form -->\n");
      out.write("    <script src='/SuiviRegime/js/jquery.min.js'></script>\n");
      out.write("    <script src='/SuiviRegime/js/bootstrap.min.js'></script>\n");
      out.write("    <script src=\"/SuiviRegime/js/login.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
