//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsSoap.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService.Banque.S6/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService.Banque.S6/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(compte))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(client))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService.Banque.S6/")]
    public partial class baseModele : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService.Banque.S6/")]
    public partial class compte : baseModele {
        
        private date dateCreationField;
        
        private int idAgenceField;
        
        private int idClientField;
        
        private int idCompteField;
        
        private int idTypeCompteField;
        
        private string numeroField;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public date dateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
                this.RaisePropertyChanged("dateCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idAgence {
            get {
                return this.idAgenceField;
            }
            set {
                this.idAgenceField = value;
                this.RaisePropertyChanged("idAgence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
                this.RaisePropertyChanged("idClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCompte {
            get {
                return this.idCompteField;
            }
            set {
                this.idCompteField = value;
                this.RaisePropertyChanged("idCompte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idTypeCompte {
            get {
                return this.idTypeCompteField;
            }
            set {
                this.idTypeCompteField = value;
                this.RaisePropertyChanged("idTypeCompte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService.Banque.S6/")]
    public partial class client : baseModele {
        
        private string adresseField;
        
        private compte[] comptesField;
        
        private date dateNaissanceField;
        
        private int idClientField;
        
        private string mailField;
        
        private string nomField;
        
        private string prenomField;
        
        private string sexeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
                this.RaisePropertyChanged("adresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comptes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public compte[] comptes {
            get {
                return this.comptesField;
            }
            set {
                this.comptesField = value;
                this.RaisePropertyChanged("comptes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date dateNaissance {
            get {
                return this.dateNaissanceField;
            }
            set {
                this.dateNaissanceField = value;
                this.RaisePropertyChanged("dateNaissance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
                this.RaisePropertyChanged("idClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
                this.RaisePropertyChanged("prenom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sexe {
            get {
                return this.sexeField;
            }
            set {
                this.sexeField = value;
                this.RaisePropertyChanged("sexe");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService.Banque.S6/", ConfigurationName="ServiceReference1.BanqueWS")]
    public interface BanqueWS {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/getAllClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/getAllClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsSoap.ServiceReference1.Exception), Action="http://WebService.Banque.S6/BanqueWS/getAllClient/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModele))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsSoap.ServiceReference1.getAllClientResponse getAllClient(WindowsFormsSoap.ServiceReference1.getAllClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/getAllClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/getAllClientResponse")]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.getAllClientResponse> getAllClientAsync(WindowsFormsSoap.ServiceReference1.getAllClientRequest request);
        
        // CODEGEN : Le paramètre 'arg0' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/AjoutClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/AjoutClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsSoap.ServiceReference1.Exception), Action="http://WebService.Banque.S6/BanqueWS/AjoutClient/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModele))]
        WindowsFormsSoap.ServiceReference1.AjoutClientResponse AjoutClient(WindowsFormsSoap.ServiceReference1.AjoutClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/AjoutClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/AjoutClientResponse")]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.AjoutClientResponse> AjoutClientAsync(WindowsFormsSoap.ServiceReference1.AjoutClientRequest request);
        
        // CODEGEN : Le paramètre 'arg0' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/updateClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/updateClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsSoap.ServiceReference1.Exception), Action="http://WebService.Banque.S6/BanqueWS/updateClient/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModele))]
        WindowsFormsSoap.ServiceReference1.updateClientResponse updateClient(WindowsFormsSoap.ServiceReference1.updateClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/updateClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/updateClientResponse")]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.updateClientResponse> updateClientAsync(WindowsFormsSoap.ServiceReference1.updateClientRequest request);
        
        // CODEGEN : Le paramètre 'arg0' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/DeleteClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/DeleteClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsSoap.ServiceReference1.Exception), Action="http://WebService.Banque.S6/BanqueWS/DeleteClient/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModele))]
        WindowsFormsSoap.ServiceReference1.DeleteClientResponse DeleteClient(WindowsFormsSoap.ServiceReference1.DeleteClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService.Banque.S6/BanqueWS/DeleteClientRequest", ReplyAction="http://WebService.Banque.S6/BanqueWS/DeleteClientResponse")]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.DeleteClientResponse> DeleteClientAsync(WindowsFormsSoap.ServiceReference1.DeleteClientRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllClient", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class getAllClientRequest {
        
        public getAllClientRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllClientResponse", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class getAllClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService.Banque.S6/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsSoap.ServiceReference1.client[] @return;
        
        public getAllClientResponse() {
        }
        
        public getAllClientResponse(WindowsFormsSoap.ServiceReference1.client[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjoutClient", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class AjoutClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService.Banque.S6/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsSoap.ServiceReference1.client arg0;
        
        public AjoutClientRequest() {
        }
        
        public AjoutClientRequest(WindowsFormsSoap.ServiceReference1.client arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjoutClientResponse", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class AjoutClientResponse {
        
        public AjoutClientResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateClient", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class updateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService.Banque.S6/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsSoap.ServiceReference1.client arg0;
        
        public updateClientRequest() {
        }
        
        public updateClientRequest(WindowsFormsSoap.ServiceReference1.client arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateClientResponse", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class updateClientResponse {
        
        public updateClientResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteClient", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class DeleteClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService.Banque.S6/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsSoap.ServiceReference1.client arg0;
        
        public DeleteClientRequest() {
        }
        
        public DeleteClientRequest(WindowsFormsSoap.ServiceReference1.client arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteClientResponse", WrapperNamespace="http://WebService.Banque.S6/", IsWrapped=true)]
    public partial class DeleteClientResponse {
        
        public DeleteClientResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueWSChannel : WindowsFormsSoap.ServiceReference1.BanqueWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueWSClient : System.ServiceModel.ClientBase<WindowsFormsSoap.ServiceReference1.BanqueWS>, WindowsFormsSoap.ServiceReference1.BanqueWS {
        
        public BanqueWSClient() {
        }
        
        public BanqueWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSoap.ServiceReference1.getAllClientResponse WindowsFormsSoap.ServiceReference1.BanqueWS.getAllClient(WindowsFormsSoap.ServiceReference1.getAllClientRequest request) {
            return base.Channel.getAllClient(request);
        }
        
        public WindowsFormsSoap.ServiceReference1.client[] getAllClient() {
            WindowsFormsSoap.ServiceReference1.getAllClientRequest inValue = new WindowsFormsSoap.ServiceReference1.getAllClientRequest();
            WindowsFormsSoap.ServiceReference1.getAllClientResponse retVal = ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).getAllClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.getAllClientResponse> WindowsFormsSoap.ServiceReference1.BanqueWS.getAllClientAsync(WindowsFormsSoap.ServiceReference1.getAllClientRequest request) {
            return base.Channel.getAllClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.getAllClientResponse> getAllClientAsync() {
            WindowsFormsSoap.ServiceReference1.getAllClientRequest inValue = new WindowsFormsSoap.ServiceReference1.getAllClientRequest();
            return ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).getAllClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSoap.ServiceReference1.AjoutClientResponse WindowsFormsSoap.ServiceReference1.BanqueWS.AjoutClient(WindowsFormsSoap.ServiceReference1.AjoutClientRequest request) {
            return base.Channel.AjoutClient(request);
        }
        
        public void AjoutClient(WindowsFormsSoap.ServiceReference1.client arg0) {
            WindowsFormsSoap.ServiceReference1.AjoutClientRequest inValue = new WindowsFormsSoap.ServiceReference1.AjoutClientRequest();
            inValue.arg0 = arg0;
            WindowsFormsSoap.ServiceReference1.AjoutClientResponse retVal = ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).AjoutClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.AjoutClientResponse> WindowsFormsSoap.ServiceReference1.BanqueWS.AjoutClientAsync(WindowsFormsSoap.ServiceReference1.AjoutClientRequest request) {
            return base.Channel.AjoutClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.AjoutClientResponse> AjoutClientAsync(WindowsFormsSoap.ServiceReference1.client arg0) {
            WindowsFormsSoap.ServiceReference1.AjoutClientRequest inValue = new WindowsFormsSoap.ServiceReference1.AjoutClientRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).AjoutClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSoap.ServiceReference1.updateClientResponse WindowsFormsSoap.ServiceReference1.BanqueWS.updateClient(WindowsFormsSoap.ServiceReference1.updateClientRequest request) {
            return base.Channel.updateClient(request);
        }
        
        public void updateClient(WindowsFormsSoap.ServiceReference1.client arg0) {
            WindowsFormsSoap.ServiceReference1.updateClientRequest inValue = new WindowsFormsSoap.ServiceReference1.updateClientRequest();
            inValue.arg0 = arg0;
            WindowsFormsSoap.ServiceReference1.updateClientResponse retVal = ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).updateClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.updateClientResponse> WindowsFormsSoap.ServiceReference1.BanqueWS.updateClientAsync(WindowsFormsSoap.ServiceReference1.updateClientRequest request) {
            return base.Channel.updateClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.updateClientResponse> updateClientAsync(WindowsFormsSoap.ServiceReference1.client arg0) {
            WindowsFormsSoap.ServiceReference1.updateClientRequest inValue = new WindowsFormsSoap.ServiceReference1.updateClientRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).updateClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSoap.ServiceReference1.DeleteClientResponse WindowsFormsSoap.ServiceReference1.BanqueWS.DeleteClient(WindowsFormsSoap.ServiceReference1.DeleteClientRequest request) {
            return base.Channel.DeleteClient(request);
        }
        
        public void DeleteClient(WindowsFormsSoap.ServiceReference1.client arg0) {
            WindowsFormsSoap.ServiceReference1.DeleteClientRequest inValue = new WindowsFormsSoap.ServiceReference1.DeleteClientRequest();
            inValue.arg0 = arg0;
            WindowsFormsSoap.ServiceReference1.DeleteClientResponse retVal = ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).DeleteClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.DeleteClientResponse> WindowsFormsSoap.ServiceReference1.BanqueWS.DeleteClientAsync(WindowsFormsSoap.ServiceReference1.DeleteClientRequest request) {
            return base.Channel.DeleteClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSoap.ServiceReference1.DeleteClientResponse> DeleteClientAsync(WindowsFormsSoap.ServiceReference1.client arg0) {
            WindowsFormsSoap.ServiceReference1.DeleteClientRequest inValue = new WindowsFormsSoap.ServiceReference1.DeleteClientRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsSoap.ServiceReference1.BanqueWS)(this)).DeleteClientAsync(inValue);
        }
    }
}
